---
- name: Modprobe zfs
  command: /sbin/modprobe zfs

- name: Remove existing zfs packages
  yum:
    name: '{{ item }}'
    state: removed
  with_items:
    - zfs
    - zfs-kmod
    - spl
    - spl-kmod
    - libzfs2
    - libnvpair1
    - libuutil1
    - libzpool2
- name: Start zfs
  service: name=zfs.target state=started enabled=yes
