- name: Manage landing page html repo
  include_role:
    name: '{{ jupyterhub_html_family }}'

- name: Manage dockerspawner
  include_role:
    name: dockerspawner
  when:
    jupyterhub_spawner in ['syzygysystemuserspawner', 'syzygyswiftsystemuserspawner', 'dockerspawner']

- name: Manage Jupyterhub Docker Cull script
  include_role:
    name: jhub-docker-cull
  when:
    jupyterhub_spawner in ['syzygysystemuserspawner', 'syzygyswiftsystemuserspawner', 'dockerspawner']

- name: Get Docker image for JupyterHub containers
  docker_image:
    name: '{{ jupyterhub_docker_container }}'
  when:
    jupyterhub_spawner in ['syzygysystemuserspawner', 'syzygyswiftsystemuserspawner', 'dockerspawner']

- name: Manage syzygyauthenticator
  include_role:
    name: syzygyauthenticator
  when: (jupyterhub_authenticator == 'syzygyauthenticator') or (jupyterhub_authenticator == 'shib')

- name: Manage Shibboleth
  include_role:
    name: shibboleth-sp
  when: jupyterhub_authenticator == 'shib'

- name: Examine groups
  debug:
    msg: 'Content of group_names is {{ group_names }}'

- name: Add a jupyter user to run things as
  user:
    name: '{{ jupyterhub_user_name }}'
    uid: '{{ jupyterhub_user_uid }}'

# Should't assume pool name here, fix later
- name: Create ZFS course container
  command: /sbin/zfs create 'tank/home/{{ jupyterhub_course_name }}'
  args:
    creates: '/tank/home/{{ jupyterhub_course_name }}'
  when: zfs_vdev_config is defined

- name: Install pycurl dependencies
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    update_cache: yes
  with_items:
    - { 'name': 'libcurl-devel', 'state': 'present' }

- name: Install pycurl
  pip:
    name: pycurl
    executable: pip3.6
  environment:
    PYCURL_SSL_LIBRARY: nss

- name: Install Jupyterhub
  pip:
    name: jupyterhub
    executable: pip3.6

- name: Install node packages
  yum:
    name: nodejs
    state: present

- name: Install configurable-http-proxy
  npm:
    name: configurable-http-proxy
    state: present
    global: yes

# Clumsily install JupyterHub dependencies
- name: Install LTIAuthenticator
  include_role:
    name: ltiauthenticator
  when: jupyterhub_authenticator == 'ltiauthenticator'

- name: Create JupyterHub Config Directory
  file:
    path: '{{ jupyterhub_srv_dir }}'
    state: directory
    mode: '0755'

- name: Add Jupyterhub Config
  template:
    src: jupyterhub_config_base.py.j2
    dest: '{{ jupyterhub_srv_dir }}/jupyterhub_config.py'
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart JupyterHub

- name: Jupyterhub Service config
  template:
    src: jupyterhub-env.j2
    dest: /etc/sysconfig/jupyterhub
    mode: 0600
    owner: root
    group: root

- name: Add User FS creation script
  copy:
    src: zfs_homedir.sh
    dest: '{{ jupyterhub_srv_dir }}'
    mode: '0700'
    owner: root
    group: root

- name: Jupyterhub Service definition
  template:
    src: jupyterhub.service.j2
    dest: /etc/systemd/system/jupyterhub.service
  notify:
    - Start JupyterHub

- name: Add jupyterhub port to to home zone (assume firewalld)
  firewalld:
    zone: 'home'
    port: '{{ jupyterhub_api_port }}/tcp'
    immediate: yes
    state: enabled
    permanent: true
