---
- name: Set html target dir
  set_fact:
    syzygy_html_dir: "{{ syzygy_html_dir }}"

- name: Create the DocumentRoot
  file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.group | default("root") }}'
    mode: '{{ item.mode | default("0755") }}'
  with_items:
    - path: '{{ syzygy_html_dir.dest }}'
      state: directory

- name: Install HTML files
  git:
    repo: '{{ syzygy_hub_landing_page_repo }}'
    version: "{{ syzygy_landing_branch }}"
    dest: '{{ syzygy_html_dir.src }}'
    ssh_opts: "-o StrictHostKeyChecking=no"
  notify:
    - Copy landing page templates

- name: Flush handlers
  meta: flush_handlers

- name: Grab html template from host
  run_once : true
  fetch:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    flat: yes
    fail_on_missing: yes
  with_items:
    - src: '{{ syzygy_html_dir.src }}/index.html'
      dest: '/var/tmp/syzygy-html-index.html'

- name: Process html template and send results back to host
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - dest: '{{ syzygy_html_dir.dest }}/index.html'
      src: '/var/tmp/syzygy-html-index.html'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create nginx config locations
  file: path={{ item.name }} state=directory owner=root group=root mode={{ item.mode }}
  with_items:
    - name: "{{ nginx_conf_path }}/http-extras.d"
      mode: "0755"
    - name: "{{ nginx_conf_path }}/http-locations.d"
      mode: "0755"
    - name: "{{ nginx_conf_path }}/https-locations.d"
      mode: "0755"
    - name: "{{ nginx_conf_path }}/https-extras.d"
      mode: "0755"
- name: Add nginx base config for syzygy https
  template:
    src: "syzygy-nginx-https.conf.j2"
    dest: "{{ nginx_conf_path }}/syzygy-nginx-https.conf"
  notify:
    - reload nginx

- name: Add nginx config for syzygy-html-redirect
  template:
    src: "syzygy-nginx-https-redirect.conf.j2"
    dest: "{{ nginx_conf_path }}/http-extras.d/syzygy-nginx-https-redirect.conf"

- name: Add nginx config for syzygy-html
  template:
    src: "syzygy-nginx-locations.conf.j2"
    dest: "{{ nginx_conf_path }}/https-locations.d/syzygy-nginx-locations.conf"

