---
- name: Install zfs-release
  yum:
    name: '{{ zfs_release_rpm }}'
    state: present
  notify:
    - Remove existing zfs packages

- name: Flush ZFS Handlers
  meta: flush_handlers

- name: Install zfs kernel module
  yum:
    name: zfs
    state: present
    update_cache: yes
  notify:
    - Modprobe zfs

- name: Ensure the ZFS kernel module is loaded
  modprobe:
    name: zfs

- name: Flush ZFS Handlers
  meta: flush_handlers

- name: Create tank zpool
  notify:
   - Start zfs
  command: /sbin/zpool create -f '{{ zfs_pool_name }}' '{{ zfs_vdev_config }}'
  args:
    creates: /tank
  when: zfs_vdev_config is defined

- name: Create ZFS home container
  command: /sbin/zfs create '{{ zfs_pool_name }}'/home
  args:
    creates: '/{{ zfs_pool_name }}/home'
  when: zfs_vdev_config is defined
